.imgjob:
  before_script:
    - echo -n "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_SERVER"
    - export BUILD_DATE=$(date +%Y-%m-%d.%H%M)
    - export CI_IMAGE="ravermeister/pgadmin4"
    - export PGADMIN_VERSION=$(cat ./VERSION)
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - gitlab-org-docker

build-release:
  stage: build
  extends: .imgjob
  script:
    - >
      docker build --pull --no-cache --force-rm --compress
      -t "$CI_IMAGE:$BUILD_DATE" --build-arg PGADMIN_VERSION .
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

publish-release:
  stage: deploy
  extends: .imgjob
  script:
    - docker push "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

###########################

build-develop:
  stage: build
  extends: .imgjob
  script:
    - >
      docker build --pull --no-cache --force-rm --compress
      -t "$CI_IMAGE:$BUILD_DATE" --build-arg PGADMIN_VERSION .
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - develop

publish-develop:
  stage: deploy
  extends: .imgjob
  script:
    - docker push "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - develop

###########################
