stages:
  - build

.imgjob:
  before_script:
    - echo -n "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_SERVER"
    - export CI_IMAGE="ravermeister/pgadmin4"
    - export PGADMIN_VERSION=$(cat ./VERSION)
  after_script:
    - curl -X POST https://hooks.microbadger.com/images/ravermeister/pgadmin4/4e8KBc0HS3NVw_vwBu7ReIgW-ro=
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - gitlab-org-docker

build-release:
  stage: build
  extends: .imgjob
  script:
    - >
      docker build --pull --no-cache --force-rm --compress
      -t "$CI_IMAGE:$PGADMIN_VERSION" --build-arg PGADMIN_VERSION .
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

###########################

build-develop:
  stage: build
  extends: .imgjob
  script:
    - >
      docker build --pull --no-cache --force-rm --compress
      -t "$CI_IMAGE:$PGADMIN_VERSION" --build-arg PGADMIN_VERSION .
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker tag "$CI_IMAGE:$PGADMIN_VERSION" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE:$PGADMIN_VERSION"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - develop

###########################
